In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
cs_df_all = pd.read_csv('/home/daisy/Documents/Research/Rovient/roivant_data/chemical_shifts.all.csv', header = None)
cs_df_all = cs_df_all.drop(labels= range(2716, 2721), axis = 0)

cs_df_all

0     1        2        3        4        5        6        7      \
0         1     C  176.870  176.870  176.870  176.870  176.870  176.870   
1         1    CA   54.847   54.842   54.846   54.841   54.826   54.835   
2         1    CB   42.077   42.066   42.071   42.070   42.053   42.066   
3         1    HA    4.344    4.339    4.344    4.339    4.326    4.335   
4         2     C  171.500  171.463  171.383  171.438  171.354  171.361   
...     ...   ...      ...      ...      ...      ...      ...      ...   
2711    464    CA   55.120   55.165   55.460   55.414   55.470   55.557   
2712    464    CB   37.141   36.953   36.191   36.157   36.248   36.279   
2713    464     H    8.417    8.485    8.575    8.560    8.556    8.545   
2714    464    HA    4.997    4.991    4.896    4.870    5.048    4.879   
2715    464     N  117.752  118.329  118.237  118.392  118.497  118.533   

        8        9      ...    39993    39994    39995    39996    39997  \
0     176.870  176.870  ...  176.870  176.870  176.870  176.870  176.870   
1      54.849   54.834  ...   54.859   54.837   54.852   54.846   54.848   
2      42.079   42.063  ...   42.084   42.062   42.078   42.069   42.072   
3       4.346    4.332  ...    4.352    4.336    4.350    4.344    4.344   
4     171.324  171.427  ...  171.591  171.413  171.344  171.344  171.573   
...       ...      ...  ...      ...      ...      ...      ...      ...   
2711   55.143   55.468  ...   55.210   55.455   55.480   55.389   55.404   
2712   37.254   36.183  ...   37.121   36.355   36.170   36.172   36.365   
2713    8.426    8.559  ...    8.388    8.617    8.619    8.642    8.590   
2714    4.950    5.060  ...    4.800    5.007    4.801    4.986    4.761   
2715  117.889  118.504  ...  118.039  119.294  119.424  119.507  119.274   

        39998    39999    40000    40001    40002  
0     176.870  176.870  176.870  176.870  176.870  
1      54.843   54.842   54.847   54.855   54.837  
2      42.068   42.070   42.073   42.080   42.074  
3       4.341    4.341    4.344    4.351    4.335  
4     171.413  171.275  171.288  171.253  171.282  
...       ...      ...      ...      ...      ...  
2711   55.394   55.114   55.163   55.096   55.146  
2712   36.221   36.857   36.965   36.886   36.935  
2713    8.634    8.670    8.632    8.663    8.640  
2714    4.934    5.076    4.955    5.120    5.081  
2715  119.133  115.910  115.805  115.831  115.891  

[2716 rows x 40003 columns]

In [3]:
cluster_assignment = np.loadtxt('/home/daisy/Documents/Research/Rovient/roivant_data/frame_cluster_assign_final.txt')
frame = cluster_assignment[:,0]
cluster = cluster_assignment[:,2].astype(int)
clusters = np.column_stack((frame,cluster))

frames_cl = []
for i in range(4):
    frame = np.where(cluster==i)[0]
    frames = np.concatenate(([-2,-1], frame))
    frames_cl.append(frames)
frames_cl

[array([   -2,    -1,   104, ..., 39988, 39989, 39997]),
 array([   -2,    -1,  4042, ..., 39993, 39994, 39996]),
 array([   -2,    -1,   202, ..., 39986, 39990, 39991]),
 array([   -2,    -1,     0, ..., 39998, 39999, 40000])]

In [4]:
def get_cluster_df(df, cluster, frames):
    cl = df[frames[cluster]+2]
    cl['average'] = cl.iloc[:,2:].mean(axis = 1)

    cs_shift = pd.DataFrame({'residue':cl[0], 'atom':cl[1], 'shift':cl['average']})
    CA_df_ave = cs_shift[(cs_shift == 'CA').any(axis=1)]
    CB_df_ave = cs_shift[(cs_shift == 'CB').any(axis=1)]
    HA_df_ave = cs_shift[(cs_shift == 'HA').any(axis=1)]
    C_df_ave = cs_shift[(cs_shift == 'C').any(axis=1)]
    H_df_ave = cs_shift[(cs_shift == 'H').any(axis=1)]
    N_df_ave = cs_shift[(cs_shift == 'N').any(axis=1)]
    
    CA_df_ave.set_index('residue', inplace=True, drop = False)
    CB_df_ave.set_index('residue', inplace=True, drop = False)
    HA_df_ave.set_index('residue', inplace=True, drop = False)
    C_df_ave.set_index('residue', inplace=True, drop = False)
    H_df_ave.set_index('residue', inplace=True, drop = False)
    N_df_ave.set_index('residue', inplace=True, drop = False)

    cs_all_ave = pd.DataFrame({'residue':CA_df_ave['residue'], 'CA':CA_df_ave['shift'], 'CB':CB_df_ave['shift'], 'HA':HA_df_ave['shift'], 'C':C_df_ave['shift'], 'H':H_df_ave['shift'], 'N':N_df_ave['shift']})
    cs_all_ave = cs_all_ave[0:-1]
    return cs_all_ave

In [5]:
cs_cl1_ave = get_cluster_df(cs_df_all, 0, frames_cl)
cs_cl2_ave = get_cluster_df(cs_df_all, 1, frames_cl)
cs_cl3_ave = get_cluster_df(cs_df_all, 2, frames_cl)
cs_cl4_ave = get_cluster_df(cs_df_all, 3, frames_cl)
cs_cl4_ave

/home/daisy/.conda/envs/labconda/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/daisy/.conda/envs/labconda/lib/python3.7/site-packages/pandas/core/ops/__init__.py:1115: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)


residue         CA         CB        HA           C         H  \
residue                                                                  
1              1  54.848037  42.073456  4.343121  176.870000       NaN   
2              2  57.578486  65.638849  5.154254  171.412711  8.594454   
3              3  62.411426  33.837423  3.767734  174.759000       NaN   
4              4  52.313919  40.177263  5.006218  172.276615  7.972906   
5              5  62.767609  35.147725  4.991772  174.161612       NaN   
...          ...        ...        ...       ...         ...       ...   
459          459  56.155233  31.470372  4.801590  174.222750  8.541278   
460          460  54.074560  44.283828  4.675496  173.970820  8.351278   
461          461  62.821744  35.369294  4.836405  174.369729       NaN   
462          462  53.852366  43.710913  4.906621  174.070850  8.478366   
463          463  61.334735  35.472012  4.556899  173.671718  8.542483   

                  N  
residue              
1               NaN  
2        114.782085  
3               NaN  
4        116.099764  
5               NaN  
...             ...  
459      118.086605  
460      119.056948  
461             NaN  
462      117.346388  
463      113.793138  

[463 rows x 7 columns]

In [6]:
def generate_weight(n):
    weights = []
    weight = []
    interval = 100*n
    num_range = np.linspace(0,100,int(100/interval+1))
    for w1 in num_range:
        for w2 in num_range:
            for w3 in num_range:
                w4 = 100-w1-w2-w3
                if w4 < 0: 
                    continue
                weight.append(w1/100)
                weight.append(w2/100)
                weight.append(w3/100)
                weight.append(w4/100)
                weights.append(weight)
                weight = []
    return weights
    
all_weights = generate_weight(0.05)


In [159]:
outdir = '/home/daisy/Documents/Research/Rovient/cluster_reweight_data/'
for weight in all_weights:
    name = str(int(weight[0]*100)) +'_'+ str(int(weight[1]*100)) +'_'+ str(int(weight[2]*100)) +'_'+ str(int(weight[3]*100)) 
    cs_cl1_reweighted = cs_cl1_ave[['CA', 'CB', 'HA', 'C', 'H', 'N']]*weight[0]
    cs_cl2_reweighted = cs_cl2_ave[['CA', 'CB', 'HA', 'C', 'H', 'N']]*weight[1]
    cs_cl3_reweighted = cs_cl3_ave[['CA', 'CB', 'HA', 'C', 'H', 'N']]*weight[2]
    cs_cl4_reweighted = cs_cl4_ave[['CA', 'CB', 'HA', 'C', 'H', 'N']]*weight[3]
    cs_cl1_reweighted.to_csv(outdir + 'c1_' + name + '.csv')
    cs_cl2_reweighted.to_csv(outdir + 'c2_' + name + '.csv')
    cs_cl3_reweighted.to_csv(outdir + 'c3_' + name + '.csv')
    cs_cl4_reweighted.to_csv(outdir + 'c4_' + name + '.csv')